# Pin name action command file

# Start of element CONN2
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, unknown, unknown)
ChangePinName(CONN2, 17, \_WR\_)
ChangePinName(CONN2, 25, \_TEST\_)
ChangePinName(CONN2, 23, \_SS\_)
ChangePinName(CONN2, 31, \_RESET\_)
ChangePinName(CONN2, 21, \_RD\_)
ChangePinName(CONN2, 1, D7)
ChangePinName(CONN2, 3, D6)
ChangePinName(CONN2, 5, D5)
ChangePinName(CONN2, 7, D4)
ChangePinName(CONN2, 9, D3)
ChangePinName(CONN2, 11, D2)
ChangePinName(CONN2, 13, D1)
ChangePinName(CONN2, 15, D0)
ChangePinName(CONN2, 27, BUSY)
ChangePinName(CONN2, 29, \_BL\_)
ChangePinName(CONN2, 19, A0)

# Start of element X1
ChangePinName(X1, 10, M2)
ChangePinName(X1, 9, M1)
ChangePinName(X1, 8, 8)
ChangePinName(X1, 7, 7)
ChangePinName(X1, 6, 6)
ChangePinName(X1, 5, 5)
ChangePinName(X1, 4, 4)
ChangePinName(X1, 3, 3)
ChangePinName(X1, 2, 2)
ChangePinName(X1, 1, 1)

# Start of element CONN1
ChangePinName(CONN1, 2, 2)
ChangePinName(CONN1, 1, 1)

# Start of element U1
ChangePinName(U1, unknown, unknown)
ChangePinName(U1, unknown, unknown)
ChangePinName(U1, 3, VB)
ChangePinName(U1, 40, VOUT/+3.3v)
ChangePinName(U1, 39, VU/USBout)
ChangePinName(U1, 20, p20)
ChangePinName(U1, 19, p19)
ChangePinName(U1, 18, p18)
ChangePinName(U1, 17, p17)
ChangePinName(U1, 16, p16)
ChangePinName(U1, 15, p15)
ChangePinName(U1, 14, p14/rx)
ChangePinName(U1, 13, p13/tx/sck)
ChangePinName(U1, 12, p12/miso)
ChangePinName(U1, 11, p11/mosi)
ChangePinName(U1, 10, p10/rx/scl)
ChangePinName(U1, 9, p9/tx/sda)
ChangePinName(U1, 8, p8)
ChangePinName(U1, 7, p7/sck)
ChangePinName(U1, 6, p6/miso)
ChangePinName(U1, 5, p5/mosi)
ChangePinName(U1, 4, \_nR\_)
ChangePinName(U1, 30, p30/rd)
ChangePinName(U1, 29, p29/td)
ChangePinName(U1, 28, p28/tx/sda)
ChangePinName(U1, 27, p27/rx/scl)
ChangePinName(U1, 26, p26)
ChangePinName(U1, 25, p25)
ChangePinName(U1, 24, p24)
ChangePinName(U1, 23, p23)
ChangePinName(U1, 22, p22)
ChangePinName(U1, 21, p21)
ChangePinName(U1, 34, TD-)
ChangePinName(U1, 33, TD+)
ChangePinName(U1, 36, RD-)
ChangePinName(U1, 35, RD+)
ChangePinName(U1, 38, IF-)
ChangePinName(U1, 37, IF+)
ChangePinName(U1, 32, D-)
ChangePinName(U1, 31, D+)

# Start of element U3
ChangePinName(U3, unknown, unknown)
ChangePinName(U3, unknown, unknown)
ChangePinName(U3, 9, QHs)
ChangePinName(U3, 10, SRCLR)
ChangePinName(U3, 4, QE)
ChangePinName(U3, 5, QF)
ChangePinName(U3, 6, QG)
ChangePinName(U3, 7, QH)
ChangePinName(U3, 3, QD)
ChangePinName(U3, 2, QC)
ChangePinName(U3, 1, QB)
ChangePinName(U3, 15, QA)
ChangePinName(U3, 14, SER)
ChangePinName(U3, 11, SRCLK)
ChangePinName(U3, 12, RCLK)
ChangePinName(U3, 13, G)

# Start of element U2
ChangePinName(U2, unknown, unknown)
ChangePinName(U2, unknown, unknown)
ChangePinName(U2, 9, QHs)
ChangePinName(U2, 10, SRCLR)
ChangePinName(U2, 4, QE)
ChangePinName(U2, 5, QF)
ChangePinName(U2, 6, QG)
ChangePinName(U2, 7, QH)
ChangePinName(U2, 3, QD)
ChangePinName(U2, 2, QC)
ChangePinName(U2, 1, QB)
ChangePinName(U2, 15, QA)
ChangePinName(U2, 14, SER)
ChangePinName(U2, 11, SRCLK)
ChangePinName(U2, 12, RCLK)
ChangePinName(U2, 13, G)
